#! /bin/sh

killall -q sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
killall -q picom
picom &
killall -q feh
feh --bg-fill /home/myu/Pictures/673189.png &
killall -q polybar
polybar Miku &
fcitx -d &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config automatic_scheme 	 alternate

bspc config border_width         4
bspc config normal_border_color  "#dab0d1"
bspc config focused_border_color "#9dd7de"

bspc config window_gap           20
bspc config top_padding 	 22

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
