#! /bin/sh

# Startup programs
killall -q sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
killall -q picom
picom &
killall -q feh
feh --bg-fill /home/myu/Pictures/673189.png &
$HOME/.config/polybar/launch.sh &
fcitx -d &

# Monitor
bspc monitor -d 一 二 三 四 五
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Window
bspc config automatic_scheme 	 alternate
bspc config honor_size_hints true

# Borders 
bspc config border_width         2
bspc config normal_border_color  "#dab0d1"
bspc config focused_border_color "#9dd7de"

# Padding and gapping
bspc config window_gap           20
bspc config top_padding 	 22

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp-2.10 desktop='^5' follow=on
bspc rule -a discord desktop='^2' state=tiled follow=on monocle
bspc rule -a Renoise desktop='^3' state=tiled
