#! /bin/sh

# Startup programs
killall -q sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
killall -q picom
picom &
killall -q feh
feh --bg-fill /home/myu/Pictures/673189.png 
$HOME/.config/polybar/launch.sh &
fcitx5 -d &
killall -q dunst
dunst &

# Monitor
bspc monitor -d 一 二 三 四 五
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
# Dual Monitor 
if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
    xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal --right-of eDP1
    # Workspaces
    bspc monitor HDMI1 -d 六 七 八 九 十
else
    xrandr --output HDMI1 --off
    # Remove nodes
    while bspc node @V: --kill; do
        :
    done
    while bspc node @VI: --kill; do
        :
    done
    while bspc node @VII: --kill; do
        :
    done
    while bspc node @VIII: --kill; do
        :
    done
    # Remove workspaces
    bspc desktop -r V VI VII VIII
    # Remove monitor
    bspc monitor HDMI1 -r
fi

# Window
bspc config automatic_scheme 	 alternate
bspc config honor_size_hints true

# Borders 
bspc config border_width         5
bspc config normal_border_color  "#dab0d1"
bspc config focused_border_color "#9dd7de"

# Padding and gapping
bspc config window_gap           15
bspc config top_padding 	 			 20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp-2.10 desktop='^5' follow=on
bspc rule -a discord desktop='^2' state=tiled follow=on monocle
bspc rule -a Renoise desktop='^3' state=tiled
